name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["--features sync", "--no-default-features --features sync,rustls-tls", "--all-features"]

    steps:
    - uses: actions/checkout@v2

    # - name: Run cargo fmt
    #   uses: actions-rs/cargo@v1
    #   with:
    #     command: fmt
    #     args: -- --check

    - name: Run cargo clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test ${{ matrix.features }} -- --test-threads=1
      env:
        SERVICE_ACCOUNT_JSON: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        TEST_BUCKET: cloud-storage-rs-test-bucket
